version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: icecream_truck_api_development
      MYSQL_USER: truckuser
      MYSQL_PASSWORD: password

  web:
    build: .
    container_name: icecream_truck_api
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/railsapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://truckuser:password@db:3306/icecream_truck_api_development

volumes:
  dbdata:
